### ISSUE TITLE
java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by clagio** [PLOS/content-repo#95]
Hello,
I'm trying deploying content-repo-1.2.0.war and rhino-2.2.1.war tomcat but for both I have the following error:

```
09-Aug-2017 15:08:25.249 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Cannot create JDBC driver of class '' for connect URL 'null'
java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:315)
        at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2151)
        at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2037)
        at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1543)
        at org.springframework.orm.hibernate3.LocalDataSourceConnectionProvider.getConnection(LocalDataSourceConnectionProvider.java:85)
        at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:113)
        at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2836)
        at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2832)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:793)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:715)
        at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:189)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)

```

No errors with wombat.. I tried both on tomcat7 and tomcat8, both default installation, and following the instructions at https://plos.github.io/ambraproject/Docs-Home.html.. I'm missing something? Seems a driver issue, but I added the mysql libraries to the lib folder..

**Comment by anilop** [comment]
Hm...I am a bit perplexed as well.
We use tomcat6 not tomcat 7 or 8 here to build and I haven't seen this error.  Maybe try tomcat6? 
Some other things you might doublecheck:
- making sure you are using JAVA8
- did you already setup your configuration files?
- did you create your database?

**Comment by clagio** [comment]
sorry wasn't an ambra issue. The mysql connector jar had some issues.. redownloading it fixed the problem
